apiVersion: apps/v1
kind: Deployment
metadata:
  name: elk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elk
  template:
    metadata:
      labels:
        app: elk
    spec:
      containers:
        - name: elk
          image: nshou/elasticsearch-kibana
          ports:
            - name: kibana
              containerPort: 5601
            - name: elasticsearch
              containerPort: 9200
         
          volumeMounts:
            - name: data-volume
              mountPath: /data
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: ws-storage
---
apiVersion: v1
kind: Service
metadata:
  name: elk
spec:
  type: NodePort
  selector:
    app: elk
  ports:
    - name: kibana
      protocol: TCP
      port: 5601
      targetPort: 5601
      nodePort: 30005  
    - name: elasticsearch
      protocol: TCP
      port: 9200
      targetPort: 9200
      # nodePort: 30006
# create ingress
---

