apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: bitnami/kafka
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: kafka
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://kafka:9092
            - name: KAFKA_LOG_CLEANUP_POLICY
              value: compact
            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              value: "3000"
            - name: KAFKA_NUM_PARTITIONS
              value: "16"
            - name: KAFKA_LOG_CLEANER_DELETE_RETENTION_MS
              value: "20000"
            - name: KAFKA_LOG_SEGMENT_BYTES
              value: "512000"
            - name: KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS
              value: "4000"
            - name: KAFKA_ZOOKEEPER_SESSION_TIMEOUT_MS
              value: "4000"
            - name: KAFKA_ADVERTISED_PORT
              value: "9092"
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
          volumeMounts:
            - name: kafka-data
              mountPath: /var/lib/kafka/data
      volumes:
        - name: kafka-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  selector:
    app: kafka
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: <zookeeper_image>
          ports:
            - containerPort: 2181
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
          volumeMounts:
            - name: zookeeper-data
              mountPath: /data
      volumes:
        - name: zookeeper-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  selector:
    app: zookeeper
  ports:
    - name: zookeeper
      port: 2181
      targetPort: 2181