apiVersion: v1
kind: Service
metadata:
  name: elk
spec:
  type: NodePort
  selector:
    app: elk
  ports:
    - name: kibana
      protocol: TCP
      port: 5601
      targetPort: 5601
      #nodePort: 30005  
    - name: elasticsearch
      protocol: TCP
      port: 9200
      targetPort: 9200
      # nodePort: 30006




apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: elk-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: kibana-weather-station.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: elk
            port:
              number: 5601
